<?php

namespace App\Exports;

use App\Models\ACCESO_4G_Movil_Provision;

use Maatwebsite\Excel\Concerns\FromQuery;
use Maatwebsite\Excel\Concerns\Exportable;
use Maatwebsite\Excel\Concerns\WithHeadings;

ini_set('memory_limit', -1);

class ProvisionExport implements FromQuery, WithHeadings
{
    use Exportable;

    public function headings(): array
    {
        return ['enodob_name',
        'enodob_address',
        'sector_name',
        'cell_id',
        'enodob_id',
        'cellid',
        'departamento',
        'provincia',
        'distrito',
        'sub_region',
        'tac',
        'localcellid',
        'objid',
        'additionalspectrumemission',
        'aircellflag',
        'cellactivestate',
        'celladminstate',
        'cellname',
        'cellradius',
        'cellspecificoffset',
        'cpricompression',
        'crsportnum',
        'csgind',
        'customizedbandwidthcfgind',
        'dlbandwidth',
        'dlcyclicprefix',
        'dlearfcn',
        'emergencyareaidcfgind',
        'enodebfunctionname',
        'fddtddind',
        'freqband',
        'highspeedflag',
        'multirrucellflag',
        'phycellid',
        'preamblefmt',
        'qoffsetfreq',
        'rootsequenceidx',
        'txrxmode',
        'uepowermaxcfgind',
        'ulbandwidth',
        'ulcyclicprefix',
        'ulearfcncfgind',
        'workmode',
        'userlabel',
        'eucellstandbymode',
        'specialsubframepatterns',
        'subframeassignment',
        'cnopsharinggroupid',
        'csirsperiod',
        'freqpriorityforanr',
        'intrafreqanrind',
        'crsportmap',
        'mbts_name',
        'cluster_name',
        'latitud',
        'longitud',
        'modelo_rru',
        'manufacturerdata',
        'direccion',
        'mme_usn_primario',
        'mme_usn_secundario',
        'referencesignalpwr',
        'ltecellindex'];
    }

    public function query()
    {
        return ACCESO_4G_Movil_Provision::select(['enodob_name',
        'enodob_address',
        'sector_name',
        'cell_id',
        'enodob_id',
        'cellid',
        'departamento',
        'provincia',
        'distrito',
        'sub_region',
        'tac',
        'localcellid',
        'objid',
        'additionalspectrumemission',
        'aircellflag',
        'cellactivestate',
        'celladminstate',
        'cellname',
        'cellradius',
        'cellspecificoffset',
        'cpricompression',
        'crsportnum',
        'csgind',
        'customizedbandwidthcfgind',
        'dlbandwidth',
        'dlcyclicprefix',
        'dlearfcn',
        'emergencyareaidcfgind',
        'enodebfunctionname',
        'fddtddind',
        'freqband',
        'highspeedflag',
        'multirrucellflag',
        'phycellid',
        'preamblefmt',
        'qoffsetfreq',
        'rootsequenceidx',
        'txrxmode',
        'uepowermaxcfgind',
        'ulbandwidth',
        'ulcyclicprefix',
        'ulearfcncfgind',
        'workmode',
        'userlabel',
        'eucellstandbymode',
        'specialsubframepatterns',
        'subframeassignment',
        'cnopsharinggroupid',
        'csirsperiod',
        'freqpriorityforanr',
        'intrafreqanrind',
        'crsportmap',
        'mbts_name',
        'cluster_name',
        'latitud',
        'longitud',
        'modelo_rru',
        'manufacturerdata',
        'direccion',
        'mme_usn_primario',
        'mme_usn_secundario',
        'referencesignalpwr',
        'ltecellindex']);
    }
}
