<?php

namespace App\Exports;

use Maatwebsite\Excel\Concerns\FromArray;
use Maatwebsite\Excel\Concerns\Exportable;
use Maatwebsite\Excel\Concerns\WithHeadings;
use Illuminate\Support\Facades\DB; 

class PuntosCVMExport implements FromArray, WithHeadings
{
    use Exportable;

    public function headings(): array
    {
        return [
            'FECHA','ID','IDCLIENT','IDSESSION','LATITUDE','LONGITUDE', 'PACKETSENT','PACKETRECEIVED','LATENCYAVG','JITTER','dl_kbps','ul_kbps','TECH_DL','RAT4G_RSRQ','RAT4G_RSRP','RAT3G_RSCP','RAT3G_TXPOWER','RAT2G_RXLEV','RAT2G_RXQUAL','IMSI','IDCELL_DL','IDCELL_UL'
        ];
    }

    public function array(): array
    {
        return DB::select(DB::raw("SELECT B.TIMESTAMP as fecha,B.ID,B.IDCLIENT,B.IDSESSION,B.LATITUDE,B.LONGITUDE, B.PACKETSENT,B.PACKETRECEIVED,B.LATENCYAVG,B.JITTER,B.THROUGHPUT_DL_KBPS as dl_kbps,B.THROUGHPUT_UL_KBPS as ul_kbps,B.TECH_DL,B.RAT4G_RSRQ,B.RAT4G_RSRP,B.RAT3G_RSCP,B.RAT3G_TXPOWER,B.RAT2G_RXLEV,B.RAT2G_RXQUAL,B.IMSI,B.IDCELL_DL,B.IDCELL_UL FROM ( SELECT id,TIMESTAMP,IDCLIENT,IDSESSION,LATITUDE,LONGITUDE, PACKETSENT,PACKETRECEIVED,LATENCYAVG,JITTER,THROUGHPUT_DL_KBPS,THROUGHPUT_UL_KBPS, UPPER(CASE WHEN DOWNLINKDATATECHNOLOGY IN ('umts-r99','hspa+','hsdpa') THEN 'UMTS' ELSE DOWNLINKDATATECHNOLOGY END) TECH_DL, RAT4G_RSRQ,RAT4G_RSRP,RAT3G_RSCP,RAT3G_TXPOWER,RAT2G_RXLEV,RAT2G_RXQUAL, IMSI, IDCELL_DL,IDCELL_UL, UBIGEO, CASE      WHEN THROUGHPUT_DL_KBPS IS NOT NULL AND THROUGHPUT_UL_KBPS IS NOT NULL      AND THROUGHPUT_DL_KBPS > 0 AND THROUGHPUT_UL_KBPS > 0      AND UBIGEO IS NOT NULL      THEN 1 ELSE 0      END MSTRAS_VALIDAS FROM ( SELECT * FROM SMART.PRG_CVM_MTV_MYSQL WHERE JOB_NAME IN ('SpeedTest Nacional','SpeedTest Internacional') AND DOWNLINKDATATECHNOLOGY IN ('umts-r99','hspa+','lte','hsdpa') ) ) B INNER JOIN PRG_MTV_CVM_OPERADOR_LIN_RECR C ON B.UBIGEO=C.UBIGEO AND B.TECH_DL=C.TECH_DL WHERE B.MSTRAS_VALIDAS=1"));
    }
}
